:concurrency: 10
:queues:
  - critical
  - default
  - low

# use below to define a background cronjob for sidekiq worker
:scheduler:
  :schedule:
    ResetUsersDailyStreakJob:
      # every day at midnight, Singapore time
      cron: '0 0 * * * Asia/Singapore'
