:concurrency: 10
:queues:
  - critical
  - default
  - low

# use below to define a background cronjob for sidekiq worker
# :schedule:
#  schedule_name:
#    cron: '*/15 * * * *' # run every 15 minutes
#    class: SomeSidekiqWorker
