name: CI test

on: 
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

env: 
  RAILS_ENV: test
  REDIS_URL: redis://redis:6379/1
  SECRET_KEY_BASE: a2ef53880a3d391cd53549d3cf20e699cca03c3f51a09a446ac5d4425d7c46ebe51381bf033d97fabccff50140b343d23bb202deae607d003e16cf7cb5d6c848
  TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/ci_test
  MAIL_FROM: test@example.com
  CI_COMMIT_AUTHOR: github-actions[bot]
  CI_COMMIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
  CI_COMMIT_MESSAGE: "auto update redoc skip ci"

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres:12.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # placing rubocop and brakeman first to fail fast
      - name: Syntax check
        run: bundle exec rubocop -l

      - name: Vulnerability check
        run: bundle exec brakeman -w3

      - name: Setup database
        run: bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rspec spec
      
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage 