name: Generate Daily Guess Word Task

on:
  workflow_dispatch:
    inputs:
      subject_code:
        description: 'Subject Code'
        required: false
        default: '0610'
      pool_id:
        description: 'Pool ID'
        required: false
        default: ''
      from_date:
        description: 'Date From'
        required: false
        default: '2024-05-20'
      to_date:
        description: 'Date To'
        required: true
        default: '2024-05-31'
      attempts:
        description: 'Number of Attempts'
        required: true
        default: '6'
      reward_points:
        description: 'Points to Reward'
        required: true
        default: '1'

jobs:
  run-rake-task:
    runs-on: ubuntu-latest

    steps:
      - name: Generate daily challenge
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ vars.PRODUCTION_HOSTS }}
          privateKey: ${{ secrets.PRODUCTION_SSH_KEY }}
          command: |
            cd ~/edupals-docker
            docker-compose run --rm api rake daily_guess_word:generate subject_code=${{ github.event.inputs.subject_code }} from_date=${{ github.event.inputs.from_date }} to_date=${{ github.event.inputs.to_date }} attempts=${{ github.event.inputs.attempts }} reward_points=${{ github.event.inputs.reward_points }}
